name: test
on:
  push:
    branches:
      - test
jobs:

  deploy:
    name: Deploy test branch
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
                  cd test
                  git pull
                  npm i --legacy-peer-deps
                  npm run build
                  pm2 restart test