name: Generate Jest Coverage Badges

on:
  push:
    branches:
      - main

jobs:
  generate-badges:
    name: generate badge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Jest with coverage and add baddge to server
        run: | 
          npx jest --coverage --coverageReporters="json-summary"
          export coverper=$(cat coverage/coverage-summary.json | jq '.total.lines.pct')
          echo "total percentage is = $coverper"
          curl -X POST -H "Content-Type: application/json" -d '{"percentage": '"$coverper"'}' "$API_ENDPOINT"
        env: 
          API_ENDPOINT: "http://3.111.47.62:3000/badge/adddata"
